### ISSUE TITLE
Automatically adjust the new media name wherever it is in use

### ISSUE THREAD

**Issue by awrog** [david-szabo97/grav-plugin-admin-addon-media-rename#10]
Love the plugin, although you have to manually change every instance of the old name in every page where it is used. It would be great if this could be handled by the plugin.

**Comment by david-szabo97** [comment]
Sounds good, I will look into it!

**Comment by david-szabo97** [comment]
Half part of this issue is resolved in https://github.com/david-szabo97/grav-plugin-admin-addon-media-rename/commit/fc2beaeddd5e0ab4bc22dabf4b8c91d55aac709f (v1.3.0)

The part when it replaces the links on all existing pages is in development, probably I will release it next week or so. Depends on my free time.
