### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jojss** [david-szabo97/grav-plugin-admin-addon-media-rename#8]
Hi! I'm getting this error:

can u help me?
thankss

![error](https://cloud.githubusercontent.com/assets/28639905/25979438/dcf5e8cc-369e-11e7-8c39-9b9f91e5f74d.JPG)

**Comment by david-szabo97** [comment]
Hi there!

`File not found` error happens when it fails to find the file you would like to rename. It can happen in situations like:
* Deleting the file through file explorer and not refreshing the page editor
* Renaming the file through file explorer and not refreshing the page editor

Does the error pop for all media files or just a specific one? Can you send me a screenshot of the popup window before pressing the rename button? Or just write down the original name, old extension, new name, new extension.

I hope we can figure out the root of the problem! Looking forward to your reply.

EDIT:
I pushed an update which makes the error text more informative. It will now tell you the path the plugin tried to use so you can investigate it.

**Comment by jojss** [comment]
this is happening in all media files!

here are the screenshots:

![error1](https://cloud.githubusercontent.com/assets/28639905/26009327/b757d474-371e-11e7-8978-24edee674e65.JPG)

![error2](https://cloud.githubusercontent.com/assets/28639905/26009326/b7572d9e-371e-11e7-9992-6af01c6b3bbb.JPG)

**Comment by david-szabo97** [comment]
Pushed an update.
Let me know if that fixes it for you.

**Comment by jojss** [comment]
yeah! Now it's working perfectly

thanks
